version: "2"
sql:
  - engine: "postgresql"
    queries: "../../internal/postgres/queries/*.sql"
    schema: "../../internal/postgres/migrations/*.sql"
    gen:
      go:
        package: "generated"
        out: "../../internal/postgres/generated"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        sql_package: "pgx/v5"
        overrides:
          - db_type: "timestamptz"
            go_type: "time.Time"
